[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterInterLinks = "d12716ef-a0f6-4df4-a9f1-a5a34e75c656"
SPICE = "5bab7191-041a-5c2e-a744-024b9c3a5062"
SPICEApplications = "e12e0822-0612-48d4-a4bb-92984dd6b6ec"

[sources]
SPICE = {path = ".."}
SPICEApplications = {path = "../lib/SPICEApplications"}

[compat]
Documenter = "1"
